"""Adding sponsored listing function

Revision ID: 861ee8226f12
Revises: 9f73a0916df3
Create Date: 2025-07-28 14:22:37.353340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861ee8226f12'
down_revision = '9f73a0916df3'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sponsored', sa.Boolean(), nullable=False, server_default='0')) # <--- MODIFIED LINE

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('is_sponsored')

    # ### end Alembic commands ###
