"""Add listing and category models

Revision ID: f2963b81a5d6
Revises: cda090b2fa73
Create Date: 2025-07-25 12:10:57.626544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2963b81a5d6'
down_revision = 'cda090b2fa73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('website_url')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
